#ifndef __DEFINES_H_
#define __DEFINES_H_

#define MQTT_MAX_PACKET_SIZE 2500
#define MQTT_MAX_TRANSFER_SIZE 2500

#define UART_MAX_TRANSFER_SIZE (uint16_t)2500

#define STATIC_JSON_BUFFER_SIZE 2500

#define DEFAULT_TIMEOUT_S 2000



#endif